### ISSUE TITLE
[Personal] Are you OK?

### ISSUE THREAD

**Issue by soulchainer** [aghuntley/aghuntley.github.io#1]
Just that.

Sorry to ask it here, but we just realized a few hours ago you were gone from all the social networks all of a sudden.

It's OK if you want to cut all internet contact because it's too much distraction to you or something like that, but if that's not the case and you have problems or something, it would be nice to know about it.

I hope you're OK ;_;. Please, don't delete github also >_<. I won't bug you more, we only want to know if you're OK. And you left no more contact method than this.

If so, farewell, Ainsley. I wish you the best ^^. Good luck with everything!

Note: I will delete this message later.

**Comment by aghuntley** [comment]
I'm good, sorry about that!!! thanks for checking up though. I've eliminated all distractions until I finish up my grad school capstone since things have gotten really hectic. I'll be making a new twitter after graduation in may and transferring my medium posts to the wp blog im working on. I appreciate the check up man, it was kind of sudden haha just a lot of anxiety with school. hope your doing well and once again I appreciate it!! I can be reached through here for the next few weeks

**Comment by soulchainer** [comment]
I'm glad to hear that! I will notice Sasha and Animesh about it :D.
Good luck with that. I will distract you no more. Remember us when you come back! T_T.
I'm closing this issue :D.
